# Generated by Django 3.0.3 on 2020-04-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kyobo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=500, null=True)),
                ('title', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=200)),
                ('review', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'kyobos',
            },
        ),
    ]
